# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
