# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161129_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='qr_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr'),
        ),
    ]
